services:
  - type: web
    name: pothole-backend
    runtime: python
    repo: https://github.com/Murtazahd04/pothole_detection-website
    plan: free
    region: oregon
    buildCommand: |
      cd pothole-backend
      pip install -r requirements.txt
    startCommand: |
      cd pothole-backend
      gunicorn app:app --timeout 120 --workers 2
    envVars:
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production